//* public
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

//* provider
import { Providers } from './providers';

//* font config
const inter = Inter({ subsets: ['latin'] });

//* fontawesome
import '/FontAwesome.Pro.6.4.2/css/all.css';

//* metadata
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <Providers>
                    {/* main section */}
                    <main>{children}</main>
                </Providers>
            </body>
        </html>
    );
}
