//* public
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

//* provider
import { Providers } from './providers';

//* font config
const inter = Inter({ subsets: ['latin'] });

//* fontawesome
import '/FontAwesome.Pro.6.4.2/css/all.css';

//* components
import MenuContainer from '@/components/sidebars/menu/menu-container';
import MainHeader from '@/components/ui-kits/main-header';

//* metadata
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <Providers>
                    {/* menu section */}
                    <MenuContainer />

                    {/* main header */}
                    <MainHeader />

                    {/* main section */}
                    <main className='main-section'>{children}</main>
                </Providers>
            </body>
        </html>
    );
}
